[package]
name = "panduza-rust-platform"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]



tokio = { version = "1", features = ["full", "tracing"] }

# --- TRACING ---

# Trace instrumentation at disabled levels will be skipped and will not even be present    
# in the resulting binary unless the verbosity level is specified dynamically. 
#  This level is configured separately for release and debug builds.
tracing = { version = "0.1", features = ["max_level_debug", "release_max_level_warn"] }
tracing-subscriber = "0.3"


console-subscriber = "0.2.0"



rumqttc = "0.24.0"

