[package]
name = "panduza-rust-platform"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# Main async framework for the platform
tokio = { version = "1", features = ["full", "tracing"] }

# MQTT async client
rumqttc = "0.24.0"

# Async trait support
async-trait = "0.1.77"

# Futures support
futures = "0.3.17"

# Json serialization & deserialization
serde_json = "1.0.114"

# Regex management
regex = "1.10.3"

# Bytes array management
bytes = "1.5.0"

# Bitflags
bitflags = "2.5.0"

# Trace instrumentation at disabled levels will be skipped and will not even be present
# in the resulting binary unless the verbosity level is specified dynamically.
# This level is configured separately for release and debug builds.
tracing = { version = "0.1", features = [
    # "max_level_off",
    # "max_level_error",
    # "max_level_warn",
    # "max_level_info",
    # "max_level_debug",
    "max_level_trace",
    # "release_max_level_off",
    # "release_max_level_error",
    # "release_max_level_warn",
    # "release_max_level_info",
    # "release_max_level_debug",
    "release_max_level_trace"
]}

# 
tracing-core = { version = "0.1.32" }

# Fmt subscriber
tracing-subscriber = "0.3"

# To see instrumentation through tokio console
console-subscriber = { version="0.2.0", optional = true }

[features]

# Enable tracing in stdout
trac-fmt = []

# Enable tracing in tokio console
trac-console = [ "console-subscriber" ]


