name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  run-some-basic-tests:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ job.needs.build.outcome == 'success' }}
    steps:
      - uses: actions/checkout@v4
      - name: Download artifacts from build job
        uses: actions/download-artifact@v3

  
